HAM_Hideout_B2F_MapScripts::
	.byte 0


NPC_HAM_HIDEOUT_1::
	lock
	faceplayer
	namebox NPC_HAM_HIDEOUT_1_Text_0
	msgbox NPC_HAM_HIDEOUT_1_Text_1
	closemessage
	hidenamebox
	release
	end


NPC_HAM_HIDEOUT_2::
	lock
	faceplayer
	namebox NPC_HAM_HIDEOUT_1_Text_0
	msgbox NPC_HAM_HIDEOUT_2_Text_0
	closemessage
	hidenamebox
	release
	end


NPC_HAM_HIDEOUT_3::
	lock
	faceplayer
	namebox NPC_HAM_HIDEOUT_1_Text_0
	msgbox NPC_HAM_HIDEOUT_3_Text_0
	closemessage
	hidenamebox
	release
	end


NPC_HAM_HIDEOUT_4::
	lock
	faceplayer
	namebox NPC_HAM_HIDEOUT_1_Text_0
	msgbox NPC_HAM_HIDEOUT_4_Text_0
	closemessage
	hidenamebox
	release
	end


NPC_HAM_HIDEOUT_5::
	lock
	faceplayer
	namebox NPC_HAM_HIDEOUT_1_Text_0
	msgbox NPC_HAM_HIDEOUT_5_Text_0
	closemessage
	hidenamebox
	release
	end


NPC_HAM_HIDEOUT_6::
	lock
	faceplayer
	namebox NPC_HAM_HIDEOUT_1_Text_0
	msgbox NPC_HAM_HIDEOUT_6_Text_0
	closemessage
	hidenamebox
	release
	end


NPC_HAM_HIDEOUT_7::
	lock
	faceplayer
	namebox NPC_HAM_HIDEOUT_1_Text_0
	msgbox NPC_HAM_HIDEOUT_7_Text_0
	closemessage
	hidenamebox
	release
	end


NPC_HAM_HIDEOUT_8::
	lock
	faceplayer
	namebox NPC_HAM_HIDEOUT_1_Text_0
	msgbox NPC_HAM_HIDEOUT_8_Text_0
	closemessage
	hidenamebox
	release
	end


NPC_HAM_HIDEOUT_9::
	lock
	faceplayer
	namebox NPC_HAM_HIDEOUT_1_Text_0
	msgbox NPC_HAM_HIDEOUT_9_Text_0
	closemessage
	hidenamebox
	release
	end


NPC_HAM_HIDEOUT_10::
	lock
	faceplayer
	namebox NPC_HAM_HIDEOUT_1_Text_0
	msgbox NPC_HAM_HIDEOUT_10_Text_0
	closemessage
	hidenamebox
	release
	end


NPC_HAM_HIDEOUT_11::
	lock
	faceplayer
	namebox NPC_HAM_HIDEOUT_1_Text_0
	msgbox NPC_HAM_HIDEOUT_11_Text_0
	closemessage
	hidenamebox
	release
	end


NPC_HAM_HIDEOUT_12::
	lock
	faceplayer
	namebox NPC_HAM_HIDEOUT_1_Text_0
	msgbox NPC_HAM_HIDEOUT_12_Text_0
	closemessage
	hidenamebox
	release
	end


NPC_HAM_HIDEOUT_13::
	lock
	faceplayer
	namebox NPC_HAM_HIDEOUT_1_Text_0
	msgbox NPC_HAM_HIDEOUT_13_Text_0
	closemessage
	hidenamebox
	release
	end


NPC_HAM_HIDEOUT_14::
	lock
	faceplayer
	namebox NPC_HAM_HIDEOUT_1_Text_0
	msgbox NPC_HAM_HIDEOUT_14_Text_0
	closemessage
	hidenamebox
	release
	end


NPC_HAM_HIDEOUT_15::
	lock
	faceplayer
	namebox NPC_HAM_HIDEOUT_1_Text_0
	msgbox NPC_HAM_HIDEOUT_15_Text_0
	closemessage
	hidenamebox
	release
	end


NPC_HAM_HIDEOUT_16::
	lock
	faceplayer
	namebox NPC_HAM_HIDEOUT_1_Text_0
	msgbox NPC_HAM_HIDEOUT_15_Text_0
	closemessage
	hidenamebox
	release
	end


BATTLE_HAM_HIDEOUT_GRUNT_1::
	trainerbattle_single TRAINER_HAM_HIDEOUT_GRUNT_1, BATTLE_HAM_HIDEOUT_GRUNT_1_Text_0, BATTLE_HAM_HIDEOUT_GRUNT_1_Text_1
	namebox BATTLE_HAM_HIDEOUT_GRUNT_1_Text_2
	msgbox BATTLE_HAM_HIDEOUT_GRUNT_1_Text_3
	hidenamebox
	release
	end


BATTLE_HAM_HIDEOUT_GRUNT_2::
	trainerbattle_single TRAINER_HAM_HIDEOUT_GRUNT_2, BATTLE_HAM_HIDEOUT_GRUNT_2_Text_0, BATTLE_HAM_HIDEOUT_GRUNT_2_Text_1
	namebox BATTLE_HAM_HIDEOUT_GRUNT_1_Text_2
	msgbox BATTLE_HAM_HIDEOUT_GRUNT_2_Text_2
	hidenamebox
	release
	end


BATTLE_HAM_HIDEOUT_GRUNT_3::
	trainerbattle_single TRAINER_HAM_HIDEOUT_GRUNT_3, BATTLE_HAM_HIDEOUT_GRUNT_3_Text_0, BATTLE_HAM_HIDEOUT_GRUNT_3_Text_1
	namebox BATTLE_HAM_HIDEOUT_GRUNT_1_Text_2
	msgbox BATTLE_HAM_HIDEOUT_GRUNT_3_Text_2
	hidenamebox
	release
	end


BATTLE_HAM_HIDEOUT_GRUNT_4::
	trainerbattle_single TRAINER_HAM_HIDEOUT_GRUNT_4, BATTLE_HAM_HIDEOUT_GRUNT_4_Text_0, BATTLE_HAM_HIDEOUT_GRUNT_4_Text_1
	namebox BATTLE_HAM_HIDEOUT_GRUNT_1_Text_2
	msgbox BATTLE_HAM_HIDEOUT_GRUNT_4_Text_2
	hidenamebox
	release
	end


BATTLE_HAM_HIDEOUT_GRUNT_5::
	trainerbattle_single TRAINER_HAM_HIDEOUT_GRUNT_5, BATTLE_HAM_HIDEOUT_GRUNT_5_Text_0, BATTLE_HAM_HIDEOUT_GRUNT_5_Text_1
	namebox BATTLE_HAM_HIDEOUT_GRUNT_1_Text_2
	msgbox BATTLE_HAM_HIDEOUT_GRUNT_5_Text_2
	hidenamebox
	release
	end


BATTLE_HAM_HIDEOUT_GRUNT_6::
	trainerbattle_single TRAINER_HAM_HIDEOUT_GRUNT_6, BATTLE_HAM_HIDEOUT_GRUNT_6_Text_0, BATTLE_HAM_HIDEOUT_GRUNT_6_Text_1
	namebox BATTLE_HAM_HIDEOUT_GRUNT_1_Text_2
	msgbox BATTLE_HAM_HIDEOUT_GRUNT_6_Text_2
	hidenamebox
	release
	end


BATTLE_HAM_HIDEOUT_GRUNT_7::
	trainerbattle_single TRAINER_HAM_HIDEOUT_GRUNT_7, BATTLE_HAM_HIDEOUT_GRUNT_7_Text_0, BATTLE_HAM_HIDEOUT_GRUNT_7_Text_1
	namebox BATTLE_HAM_HIDEOUT_GRUNT_1_Text_2
	msgbox BATTLE_HAM_HIDEOUT_GRUNT_7_Text_2
	hidenamebox
	release
	end


BATTLE_HAM_HIDEOUT_GRUNT_8::
	trainerbattle_single TRAINER_HAM_HIDEOUT_GRUNT_8, BATTLE_HAM_HIDEOUT_GRUNT_8_Text_0, BATTLE_HAM_HIDEOUT_GRUNT_8_Text_1
	namebox BATTLE_HAM_HIDEOUT_GRUNT_1_Text_2
	msgbox BATTLE_HAM_HIDEOUT_GRUNT_8_Text_2
	hidenamebox
	release
	end


BATTLE_HAM_HIDEOUT_GRUNT_9::
	trainerbattle_single TRAINER_HAM_HIDEOUT_GRUNT_9, BATTLE_HAM_HIDEOUT_GRUNT_9_Text_0, BATTLE_HAM_HIDEOUT_GRUNT_9_Text_1
	namebox BATTLE_HAM_HIDEOUT_GRUNT_1_Text_2
	msgbox BATTLE_HAM_HIDEOUT_GRUNT_9_Text_2
	hidenamebox
	release
	end


BATTLE_HAM_HIDEOUT_GRUNT_10::
	trainerbattle_single TRAINER_HAM_HIDEOUT_GRUNT_10, BATTLE_HAM_HIDEOUT_GRUNT_10_Text_0, BATTLE_HAM_HIDEOUT_GRUNT_10_Text_1
	namebox BATTLE_HAM_HIDEOUT_GRUNT_1_Text_2
	msgbox BATTLE_HAM_HIDEOUT_GRUNT_10_Text_2
	hidenamebox
	release
	end


NPC_HAM_HIDEOUT_1_Text_0:
	.string "H.A.M Member$"

NPC_HAM_HIDEOUT_1_Text_1:
	.string "We will not tolerate anyone with an\n"
	.string "opinion differing from our own.\p"
	.string "That is the path of disaster.$"

NPC_HAM_HIDEOUT_2_Text_0:
	.string "Before I joined H.A.M my family was\n"
	.string "killed by goblins.\p"
	.string "Now I feel like I have found my life's\n"
	.string "calling right here.$"

NPC_HAM_HIDEOUT_3_Text_0:
	.string "I quite like it here honestly.\p"
	.string "One thing bugs me however.\p"
	.string "Why did the leaders decide on the robes\n"
	.string "being pink?\n"
	.string "{PAUSE 15}Is there some symbolism I am not\l"
	.string "getting?$"

NPC_HAM_HIDEOUT_4_Text_0:
	.string "Don't tell any of the other grunts, but\n"
	.string "I got a thing for Babe.\p"
	.string "Do you know anything that might help me\n"
	.string "get closer to her?\n"
	.string "There is a limit to how much hatred\l"
	.string "against monsters can bring people\l"
	.string "together...$"

NPC_HAM_HIDEOUT_5_Text_0:
	.string "We are going to make Lumbridge great\n"
	.string "again.\n"
	.string "Then the world will follow.$"

NPC_HAM_HIDEOUT_6_Text_0:
	.string "If you do not agree with my opinion you\n"
	.string "are my enemy, that is how the world\l"
	.string "works.$"

NPC_HAM_HIDEOUT_7_Text_0:
	.string "The dog I grew up with evolved into a\n"
	.string "green monstrosity.\p"
	.string "I still like it, but now it's the thing we\n"
	.string "are trying to vanquish from the world.\p"
	.string "Am I in the wrong for not wanting to\n"
	.string "abandon my friend?$"

NPC_HAM_HIDEOUT_8_Text_0:
	.string "We might use monsters to fight\n"
	.string "monsters, but we have standards.\p"
	.string "Dogs, spiders, cows, pigs, sheep, and\n"
	.string "cats have been friends and allies to\l"
	.string "humans for centuries.\n"
	.string "Now they stand with us against the\l"
	.string "scourge that are monsters!$"

NPC_HAM_HIDEOUT_9_Text_0:
	.string "I miss not living in a cave.$"

NPC_HAM_HIDEOUT_10_Text_0:
	.string "Johanhus is an idealist, he wants to\n"
	.string "solve conflict with words alone.\p"
	.string "So far it hasn't really worked, though.$"

NPC_HAM_HIDEOUT_11_Text_0:
	.string "Babe and Patty are recent admins\n"
	.string "recruited by Sigmund for their hard\l"
	.string "work.\n"
	.string "Patty's hard work that is, I don't know\l"
	.string "what Babe did...$"

NPC_HAM_HIDEOUT_12_Text_0:
	.string "Babe is really aloof.\p"
	.string "It's really hard to tell what's going on\n"
	.string "in her head.$"

NPC_HAM_HIDEOUT_13_Text_0:
	.string "I hear Patty used to be a wizard in the\n"
	.string "Wizards' Tower before she joined us.\p"
	.string "She was thrown out due to rash and\n"
	.string "feisty decisions apparently.$"

NPC_HAM_HIDEOUT_14_Text_0:
	.string "Sigmund is an extremist among us.\p"
	.string "He doesn't mind flooding a cavern of\n"
	.string "goblins if it means they will all die.\n"
	.string "Personally I get that.$"

NPC_HAM_HIDEOUT_15_Text_0:
	.string "Sigmund believes power and might makes\n"
	.string "right, so we in H.A.M will become the most\l"
	.string "powerful organisation in Gielinor.$"

BATTLE_HAM_HIDEOUT_GRUNT_1_Text_0:
	.string "I bet you're wondering how I ended up\n"
	.string "here.$"

BATTLE_HAM_HIDEOUT_GRUNT_1_Text_1:
	.string "Urgh...$"

BATTLE_HAM_HIDEOUT_GRUNT_1_Text_2:
	.string "H.A.M Grunt$"

BATTLE_HAM_HIDEOUT_GRUNT_1_Text_3:
	.string "When I signed up to become a member, I\n"
	.string "was never told that our headquarters\l"
	.string "was in a cave.\p"
	.string "The Black Knights have a whole\n"
	.string "fortress...$"

BATTLE_HAM_HIDEOUT_GRUNT_2_Text_0:
	.string "I've only been a member for a few days...\p"
	.string "Do you know where the toilets are?$"

BATTLE_HAM_HIDEOUT_GRUNT_2_Text_1:
	.string "Aaaaaahhhh!$"

BATTLE_HAM_HIDEOUT_GRUNT_2_Text_2:
	.string "Please tell me it's not just a hole in\n"
	.string "the floor...$"

BATTLE_HAM_HIDEOUT_GRUNT_3_Text_0:
	.string "I've not had a good night's sleep in\n"
	.string "weeks!\p"
	.string "I'm going to take my frustrations on\n"
	.string "you!$"

BATTLE_HAM_HIDEOUT_GRUNT_3_Text_1:
	.string "My back!$"

BATTLE_HAM_HIDEOUT_GRUNT_3_Text_2:
	.string "Have you seen how many of us there are\n"
	.string "compared to how many beds we have?\p"
	.string "There's a rota, but most nights it's\n"
	.string "whatever space we can find on the\l"
	.string "floor.$"

BATTLE_HAM_HIDEOUT_GRUNT_4_Text_0:
	.string "People like you who are friends with\n"
	.string "monsters make me sick.$"

BATTLE_HAM_HIDEOUT_GRUNT_4_Text_1:
	.string "Disgusting!$"

BATTLE_HAM_HIDEOUT_GRUNT_4_Text_2:
	.string "I can't bear to speak to a monster\n"
	.string "sympathiser like you.$"

BATTLE_HAM_HIDEOUT_GRUNT_5_Text_0:
	.string "Johanhus and Sigmund were able to build\n"
	.string "all this in a cave!\p"
	.string "With a box of scraps!$"

BATTLE_HAM_HIDEOUT_GRUNT_5_Text_1:
	.string "Gah!$"

BATTLE_HAM_HIDEOUT_GRUNT_5_Text_2:
	.string "Praise be to Johanhus and Sigmund.\p"
	.string "Where would we be without them?$"

BATTLE_HAM_HIDEOUT_GRUNT_6_Text_0:
	.string "I have been chosen by Johanhus for a\n"
	.string "special purpose.$"

BATTLE_HAM_HIDEOUT_GRUNT_6_Text_1:
	.string "I may have lost, but I won't fail him.$"

BATTLE_HAM_HIDEOUT_GRUNT_6_Text_2:
	.string "Johanhus has tasked me with searching\n"
	.string "for caches of First Age armour.\p"
	.string "I wonder why he wants it, we already\n"
	.string "have plenty of sets of much newer\l"
	.string "armour...$"

BATTLE_HAM_HIDEOUT_GRUNT_7_Text_0:
	.string "Do you think Sigmund's plans are\n"
	.string "extremist?$"

BATTLE_HAM_HIDEOUT_GRUNT_7_Text_1:
	.string "I only asked a question!$"

BATTLE_HAM_HIDEOUT_GRUNT_7_Text_2:
	.string "There are lots of mutterings around\n"
	.string "here that Sigmund's actions are\l"
	.string "dangerous and destructive.\p"
	.string "Personally, I don't think he's done\n"
	.string "enough yet.\p"
	.string "It will take a substantial amount of\n"
	.string "power to wipe out the scourge of\l"
	.string "monsters.$"

BATTLE_HAM_HIDEOUT_GRUNT_8_Text_0:
	.string "Go in peace in the name of Saradomin.\p"
	.string "May his glory shine upon you like the\n"
	.string "sun.$"

BATTLE_HAM_HIDEOUT_GRUNT_8_Text_1:
	.string "May Saradomin guide your soul to light.$"

BATTLE_HAM_HIDEOUT_GRUNT_8_Text_2:
	.string "As Saradomin is the 'Lord of Light', do\n"
	.string "you think that Johanhus and Sigmund\l"
	.string "deliberately build our base underground\l"
	.string "where the light cannot reach because\l"
	.string "they know he would be ashamed of us?$"

BATTLE_HAM_HIDEOUT_GRUNT_9_Text_0:
	.string "How dare you side with those THINGS\n"
	.string "instead of your fellow humans!$"

BATTLE_HAM_HIDEOUT_GRUNT_9_Text_1:
	.string "Traitor!$"

BATTLE_HAM_HIDEOUT_GRUNT_9_Text_2:
	.string "I used to be a farmer, you know.\p"
	.string "Until a group of hobgoblins destroyed\n"
	.string "my crops.\p"
	.string "Ruined my livelihood!\p"
	.string "Honest farmers shouldn't have to deal\n"
	.string "with that, it's why monsters should be\l"
	.string "eradicated.$"

BATTLE_HAM_HIDEOUT_GRUNT_10_Text_0:
	.string "Monsters are evil, so that means we can\n"
	.string "kill them for fun.$"

BATTLE_HAM_HIDEOUT_GRUNT_10_Text_1:
	.string "Evil, evil creatures!$"

BATTLE_HAM_HIDEOUT_GRUNT_10_Text_2:
	.string "I learned that from an old book, the\n"
	.string "'Manual of Monsters'.\p"
	.string "It had details on all different kinds of\n"
	.string "monsters and it said if they were good\l"
	.string "or evil...\n"
	.string "and most of them are evil!$"
